/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lojamarmore;

import java.util.List;
import javax.swing.JOptionPane;import javax.swing.table.DefaultTableModel;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maico
 */
public class TelaVendaMarmore extends javax.swing.JFrame {

    /**
     * Creates new form TelaVendaMarmore
     */
    public TelaVendaMarmore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipoDePedra = new javax.swing.ButtonGroup();
        bgTipoDeMarmore = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rboPiso = new javax.swing.JRadioButton();
        rboPia = new javax.swing.JRadioButton();
        rboParede = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        tglPigues = new javax.swing.JToggleButton();
        tglCarrara = new javax.swing.JToggleButton();
        tglCintilante = new javax.swing.JToggleButton();
        tglThassos = new javax.swing.JToggleButton();
        tglParana = new javax.swing.JToggleButton();
        cboCaixa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCombo = new javax.swing.JList<>();
        btnAdicionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMarmore = new javax.swing.JTable();
        btnRemover = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bgTipoDePedra.add(rboPiso);
        rboPiso.setText("Piso");

        bgTipoDePedra.add(rboPia);
        rboPia.setText("Pia");

        bgTipoDePedra.add(rboParede);
        rboParede.setText("Parede");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rboPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(rboPia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rboParede, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rboPiso)
                    .addComponent(rboPia)
                    .addComponent(rboParede)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bgTipoDeMarmore.add(tglPigues);
        tglPigues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mamore 11.jpg"))); // NOI18N
        tglPigues.setText("jToggleButton1");
        tglPigues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglPiguesActionPerformed(evt);
            }
        });

        bgTipoDeMarmore.add(tglCarrara);
        tglCarrara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marmore 22.jpg"))); // NOI18N
        tglCarrara.setText("jToggleButton2");

        bgTipoDeMarmore.add(tglCintilante);
        tglCintilante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marmore 44.jpg"))); // NOI18N
        tglCintilante.setText("jToggleButton3");
        tglCintilante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglCintilanteActionPerformed(evt);
            }
        });

        bgTipoDeMarmore.add(tglThassos);
        tglThassos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marmore 55.jpg"))); // NOI18N
        tglThassos.setText("jToggleButton4");

        bgTipoDeMarmore.add(tglParana);
        tglParana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marmore33.jpg"))); // NOI18N
        tglParana.setSelected(true);
        tglParana.setText("jToggleButton5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tglPigues, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tglCarrara, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tglCintilante, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tglThassos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(tglParana, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tglPigues, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglCarrara, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tglCintilante, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglThassos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglParana, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        cboCaixa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R$ 79 00/m² (1 caixa)", "2 caixas ", "3 caixas", "4 caixas", "5 caixas", " " }));
        cboCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCaixaActionPerformed(evt);
            }
        });

        lstCombo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Aplicação", "Velação", "Impermeabilização", "Lustração", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstCombo);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        tblMarmore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo", "Pedra", "Caixa", "Serviço"
            }
        ));
        jScrollPane2.setViewportView(tblMarmore);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        jButton2.setText("Detalhes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor Total:");

        jLabel2.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboCaixa, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglCintilanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglCintilanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglCintilanteActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
     
          String tipoDePedra = "";

        if (rboPiso.isSelected()) {
            tipoDePedra = rboPiso.getText();
        } else if (rboPia.isSelected()) {
            tipoDePedra = rboPia.getText();
        } else if (rboParede.isSelected()) {
            tipoDePedra = rboParede.getText();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um tipo!");
        }
        String tipoMarmore = "";

        if (tglPigues.isSelected()) {
            tipoMarmore = tglPigues.getText();
        } else if (tglCarrara.isSelected()) {
            tipoMarmore = tglCarrara.getText();           
        } else if (tglCintilante.isSelected()) {
                tipoMarmore = tglCintilante.getText();
        } else if (tglThassos.isSelected()) {
            tipoMarmore = tglThassos.getText();           
        } else if (tglParana.isSelected()) {
            tipoMarmore = tglParana.getText();
        } else {
            JOptionPane.showMessageDialog(rootPane, "selecione uma pedra!");
        }
            String Caixa = "";

            int indiceCaixa = cboCaixa.getSelectedIndex();
            if (indiceCaixa == 0) {
                JOptionPane.showMessageDialog(rootPane, "selecione a quantidade!");
            } else {
                Caixa = cboCaixa.getSelectedItem().toString();
            }
           
            List<String> Combo = lstCombo.getSelectedValuesList();
            String lstComboConcatenadas = "";

            for (String combo : Combo) {
                lstComboConcatenadas += Combo + "   , ";
            }

            int retorno = JOptionPane.showConfirmDialog(rootPane, "Confirma seleção?");
            if (retorno ==0){
                
                DefaultTableModel modelo = (DefaultTableModel) tblMarmore.getModel();
                modelo.addRow(new String[]{tipoDePedra,
                tipoMarmore,
                Caixa,
                lstComboConcatenadas
            });
                
            }
                                                                  
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void tglPiguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglPiguesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglPiguesActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int indiceLinha = tblMarmore.getSelectedRow();
       
       if (indiceLinha >0){
          DefaultTableModel modelo = (DefaultTableModel) tblMarmore.getModel(); 
          modelo.removeRow(indiceLinha);
       }else{ 
           JOptionPane.showMessageDialog(rootPane, "Selecione uma linha");
           
       }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
          String tipoDePedra = "";

        if (rboPiso.isSelected()) {
            tipoDePedra = rboPiso.getText();
        } else if (rboPia.isSelected()) {
            tipoDePedra = rboPia.getText();
        } else if (rboParede.isSelected()) {
            tipoDePedra = rboParede.getText();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um tipo!");
        }
        String tipoMarmore = "";

        if (tglPigues.isSelected()) {
            tipoMarmore = tglPigues.getText();
        } else if (tglCarrara.isSelected()) {
            tipoMarmore = tglCarrara.getText();           
        } else if (tglCintilante.isSelected()) {
                tipoMarmore = tglCintilante.getText();
        } else if (tglThassos.isSelected()) {
            tipoMarmore = tglThassos.getText();           
        } else if (tglParana.isSelected()) {
            tipoMarmore = tglParana.getText();
        } else {
            JOptionPane.showMessageDialog(rootPane, "selecione uma pedra!");
        }
            String Caixa = "";

            int indiceCaixa = cboCaixa.getSelectedIndex();
            if (indiceCaixa == 0) {
                JOptionPane.showMessageDialog(rootPane, "selecione a quantidade!");
            } else {
                Caixa = cboCaixa.getSelectedItem().toString();
            }
           
            List<String> Combo = lstCombo.getSelectedValuesList();
            String lstComboConcatenadas = "";

            for (String combo : Combo) {
                lstComboConcatenadas += Combo + "   , ";
            }

            int retorno = JOptionPane.showConfirmDialog(rootPane, "Confirma seleção?");
            if (retorno ==0){
                
                DefaultTableModel modelo = (DefaultTableModel) tblMarmore.getModel();
                modelo.addRow(new String[]{tipoDePedra,
                tipoMarmore,
                Caixa,
                lstComboConcatenadas
            });
                
            }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void cboCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCaixaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendaMarmore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendaMarmore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendaMarmore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendaMarmore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendaMarmore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipoDeMarmore;
    private javax.swing.ButtonGroup bgTipoDePedra;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<String> cboCaixa;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstCombo;
    private javax.swing.JRadioButton rboParede;
    private javax.swing.JRadioButton rboPia;
    private javax.swing.JRadioButton rboPiso;
    private javax.swing.JTable tblMarmore;
    private javax.swing.JToggleButton tglCarrara;
    private javax.swing.JToggleButton tglCintilante;
    private javax.swing.JToggleButton tglParana;
    private javax.swing.JToggleButton tglPigues;
    private javax.swing.JToggleButton tglThassos;
    // End of variables declaration//GEN-END:variables
}
